ceph_dir_linux: '/ceph/akrami'
ceph_dir_windows: 'X:\'
home_dir_linux: '/nfs/nhome/live/aonih'
home_dir_windows: 'H:\'
recording_dir: ['Dammy','ephys','DO79_2024-01-31_15-30-34_002']
sorter: 'kilosort2_5'
# sorter: 'spykingcircus2'
ow_flag: false
container_flag: true
sorter_dir_suffix: ''
block_idx: 0
probe_name: 'ASSY-236-P-1'