ceph_dir_linux: '/ceph/akrami'
ceph_dir_windows: 'X:\'
home_dir_linux: '/nfs/nhome/live/aonih'
home_dir_windows: 'H:\'
recording_dir: 'X:\Dammy\ephys\DO79_2024-01-25_16-07-42_001'
extra_dirs: ['X:\Dammy\ephys\DO79_2024-01-24_16-53-40_001','X:\Dammy\ephys\DO79_2024-01-24_18-03-24_002']
# extra_dirs: [['Dammy','ephys','DO79_2024-01-23_17-15-17_002'],['Dammy','ephys','DO79_2024-01-23_18-48-18_003']]

sorter: 'kilosort4'
# sorter: 'spykingcircus2'
ow_flag: false
container_flag: true
# sorter_dir_suffix: '_ks_drift'
sorter_dir_suffix: '_no_ks_drift'
rec_dir_suffix: "_no_si_drift"
block_idx: 0
probe_name: 'ASSY-325-P-1-D.json'